

const mockHourly = 
 [ { hour: '12PM',
          icon: 'partlycloudy.svg',
          temp: 47,
          condition: 'Partly Cloudy',
          yday: 353 },
        { hour: '1PM',
          icon: 'partlycloudy.svg',
          temp: 49,
          condition: 'Partly Cloudy',
          yday: 353 },
        { hour: '2PM',
          icon: 'partlycloudy.svg',
          temp: 49,
          condition: 'Partly Cloudy',
          yday: 353 },
        { hour: '3PM',
          icon: 'clear.svg',
          temp: 51,
          condition: 'Clear',
          yday: 353 },
        { hour: '4PM',
          icon: 'clear.svg',
          temp: 50,
          condition: 'Clear',
          yday: 353 },
        { hour: '5PM',
          icon: 'clear.svg',
          temp: 48,
          condition: 'Clear',
          yday: 353 },
        { hour: '6PM',
          icon: 'clear.svg',
          temp: 45,
          condition: 'Clear',
          yday: 353 },
        { hour: '7PM',
          icon: 'clear.svg',
          temp: 43,
          condition: 'Clear',
          yday: 353 },
        { hour: '8PM',
          icon: 'clear.svg',
          temp: 41,
          condition: 'Clear',
          yday: 353 },
        { hour: '9PM',
          icon: 'clear.svg',
          temp: 39,
          condition: 'Clear',
          yday: 353 },
        { hour: '10PM',
          icon: 'clear.svg',
          temp: 38,
          condition: 'Clear',
          yday: 353 },
        { hour: '11PM',
          icon: 'clear.svg',
          temp: 37,
          condition: 'Clear',
          yday: 353 },
        { hour: '12AM',
          icon: 'clear.svg',
          temp: 37,
          condition: 'Clear',
          yday: 354 },
        { hour: '1AM',
          icon: 'clear.svg',
          temp: 36,
          condition: 'Clear',
          yday: 354 },
        { hour: '2AM',
          icon: 'clear.svg',
          temp: 36,
          condition: 'Clear',
          yday: 354 },
        { hour: '3AM',
          icon: 'clear.svg',
          temp: 35,
          condition: 'Clear',
          yday: 354 },
        { hour: '4AM',
          icon: 'clear.svg',
          temp: 34,
          condition: 'Clear',
          yday: 354 },
        { hour: '5AM',
          icon: 'clear.svg',
          temp: 34,
          condition: 'Clear',
          yday: 354 },
        { hour: '6AM',
          icon: 'clear.svg',
          temp: 33,
          condition: 'Clear',
          yday: 354 },
        { hour: '7AM',
          icon: 'clear.svg',
          temp: 33,
          condition: 'Clear',
          yday: 354 },
        { hour: '8AM',
          icon: 'clear.svg',
          temp: 34,
          condition: 'Clear',
          yday: 354 },
        { hour: '9AM',
          icon: 'clear.svg',
          temp: 36,
          condition: 'Clear',
          yday: 354 },
        { hour: '10AM',
          icon: 'clear.svg',
          temp: 40,
          condition: 'Clear',
          yday: 354 },
        { hour: '11AM',
          icon: 'clear.svg',
          temp: 43,
          condition: 'Clear',
          yday: 354 },
        { hour: '12PM',
          icon: 'clear.svg',
          temp: 46,
          condition: 'Clear',
          yday: 354 },
        { hour: '1PM',
          icon: 'clear.svg',
          temp: 50,
          condition: 'Clear',
          yday: 354 },
        { hour: '2PM',
          icon: 'clear.svg',
          temp: 52,
          condition: 'Clear',
          yday: 354 },
        { hour: '3PM',
          icon: 'partlycloudy.svg',
          temp: 53,
          condition: 'Partly Cloudy',
          yday: 354 },
        { hour: '4PM',
          icon: 'partlycloudy.svg',
          temp: 53,
          condition: 'Partly Cloudy',
          yday: 354 },
        { hour: '5PM',
          icon: 'partlycloudy.svg',
          temp: 52,
          condition: 'Partly Cloudy',
          yday: 354 },
        { hour: '6PM',
          icon: 'mostlycloudy.svg',
          temp: 52,
          condition: 'Mostly Cloudy',
          yday: 354 },
        { hour: '7PM',
          icon: 'mostlycloudy.svg',
          temp: 52,
          condition: 'Mostly Cloudy',
          yday: 354 },
        { hour: '8PM',
          icon: 'cloudy.svg',
          temp: 52,
          condition: 'Overcast',
          yday: 354 },
        { hour: '9PM',
          icon: 'cloudy.svg',
          temp: 53,
          condition: 'Overcast',
          yday: 354 },
        { hour: '10PM',
          icon: 'cloudy.svg',
          temp: 53,
          condition: 'Overcast',
          yday: 354 },
        { hour: '11PM',
          icon: 'cloudy.svg',
          temp: 53,
          condition: 'Overcast',
          yday: 354 } ]

export default mockHourly