export default const mockDayArray = 

[ { day: 'Wednesday',
          icon: 'partlycloudy.svg',
          high: '51',
          low: '32',
          condition: 'Partly Cloudy',
          yday: 353 },
        { day: 'Thursday',
          icon: 'clear.svg',
          high: '55',
          low: '51',
          condition: 'Clear',
          yday: 354 },
        { day: 'Friday',
          icon: 'chancerain.svg',
          high: '57',
          low: '44',
          condition: 'Chance of Rain',
          yday: 355 },
        { day: 'Saturday',
          icon: 'rain.svg',
          high: '47',
          low: '30',
          condition: 'Rain',
          yday: 356 },
        { day: 'Sunday',
          icon: 'cloudy.svg',
          high: '37',
          low: '22',
          condition: 'Overcast',
          yday: 357 },
        { day: 'Monday',
          icon: 'clear.svg',
          high: '35',
          low: '19',
          condition: 'Clear',
          yday: 358 },
        { day: 'Tuesday',
          icon: 'partlycloudy.svg',
          high: '32',
          low: '20',
          condition: 'Partly Cloudy',
          yday: 359 },
        { day: 'Wednesday',
          icon: 'partlycloudy.svg',
          high: '33',
          low: '26',
          condition: 'Partly Cloudy',
          yday: 360 },
        { day: 'Thursday',
          icon: 'snow.svg',
          high: '35',
          low: '23',
          condition: 'Snow Showers',
          yday: 361 },
        { day: 'Friday',
          icon: 'partlycloudy.svg',
          high: '31',
          low: '18',
          condition: 'Partly Cloudy',
          yday: 362 } ]

